compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@nomicfoundation/ethereumjs-statemanager@*":
    dependencies:
      "@nomicfoundation/ethereumjs-trie": "*"
      "@nomicfoundation/ethereumjs-util": "*"
  "@nomicfoundation/ethereumjs-util@*":
    dependencies:
      buffer: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  hardhat@*:
    dependencies:
      bn.js: "*"
  mocha@*:
    dependencies:
      eth-gas-reporter: "*"
  undici-types@*:
    dependencies:
      buffer: "*"

pnpEnableEsmLoader: true
